### ISSUE TITLE
User abort: Submit failed with code 7: null

### ISSUE THREAD

**Issue by darkedges** [digital-asset/daml#5290] opened 2020-03-30 23:31 UTC
When I run the following

```bash
daml sandbox .daml\dist\quickstart-0.0.1.dar \
    --wall-clock-time \
    --address 0.0.0.0  \
    --ledgerid MyLedger \
    --auth-jwt-hs256-unsafe=secret
```

```bash
daml script --dar .daml\dist\quickstart-0.0.1.dar \
    --script-name Setup:initialize \
    --ledger-host localhost \
    --ledger-port 6865 \
    --wall-clock-time \
    --access-token-file accessToken.txt
```

I get 
```bash
Reading token from accessToken.txt...
Slf4jLogger started
Error: User abort: Submit failed with code 7: null
Exception in thread "main" com.digitalasset.daml.lf.speedy.SError$DamlEUserError
        at com.digitalasset.daml.lf.speedy.SBuiltin$SBError$.execute(SBuiltin.scala:1278)
        at com.digitalasset.daml.lf.speedy.Speedy$CtrlValue.execute(Speedy.scala:361)
        at com.digitalasset.daml.lf.speedy.Speedy$Machine.step(Speedy.scala:120)
        at com.digitalasset.daml.lf.engine.script.Runner.stepToValue$1(Runner.scala:281)
        at com.digitalasset.daml.lf.engine.script.Runner.go$1(Runner.scala:312)
        at com.digitalasset.daml.lf.engine.script.Runner.$anonfun$runExpr$7(Runner.scala:361)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
daml-helper: Received ExitFailure 1 when running
Raw command: java "-Dlogback.configurationFile=C:\\Users\\NIrving\\AppData\\Roaming\\daml\\sdk\\0.13.55\\daml-sdk/script-logback.xml" -jar "C:\\Users\\NIrving\\AppData\\Roaming\\daml\\sdk\\0.13.55\\daml-sdk/daml-sdk.jar" script --dar ".daml\\dist\\quickstart-0.0.1.dar" --script-name Setup:initialize --ledger-host localhost --ledger-port 6865 --wall-clock-time --access-token-file accessToken.txt
````
The token payload is
[accessToken.txt](https://github.com/digital-asset/daml/files/4405936/accessToken.txt)

```bash
{
  "https://daml.com/ledger-api": {
    "ledgerId": "MyLedger",
    "applicationId": "foobar",
    "admin": true
  }
}
````
Any ideas? It works if I don't use Access Tokens.

**Comment by darkedges** [comment] 2020-03-31 00:29
[failed.txt](https://github.com/digital-asset/daml/files/4406086/failed.txt)
[working.txt](https://github.com/digital-asset/daml/files/4406087/working.txt)
seems there are some differences. with an Access Token seems it misses out a chunk of something.

**Comment by cocreature** [comment] 2020-03-31 06:51
Hi @darkedges, the issue is that your token only has an `admin` claim but no `actAs` claim. An `admin` claim _only_ allows you to use the ledger API admin services which for DAML script means that you can only allocate parties. It does not allow you to act as a party. If you look at `Setup:initialize`, it allocates 4 parties and then acts as those parties. So the token payload you need is the following:

```
{
  "https://daml.com/ledger-api": {
    "ledgerId": "MyLedger",
    "applicationId": "foobar",
    "admin": true,
    "actAs": ["Alice", "Bob", "USD_Bank", "EUR_Bank"]
  }
}
```

Encoded as a token file you should end up with the following:
```
Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwczovL2RhbWwuY29tL2xlZGdlci1hcGkiOnsibGVkZ2VySWQiOiJNeUxlZGdlciIsImFwcGxpY2F0aW9uSWQiOiJmb29iYXIiLCJhZG1pbiI6dHJ1ZSwiYWN0QXMiOlsiQWxpY2UiLCJCb2IiLCJVU0RfQmFuayIsIkVVUl9CYW5rIl19fQ.xEvz-bsIFM4stLvVRvKPvHwR946V8HTG9bUk_M11uC4
```

I hope that helps!

**Comment by darkedges** [comment] 2020-03-31 08:13
@cocreature Thanks that works.

It may be worthwhile making that error more user friendly, as I tried to walk through the code and could not make any headway.

**Comment by cocreature** [comment] 2020-03-31 08:14
Yep working on that right now :+1:

**Comment by cocreature** [comment] 2020-03-31 11:08
You will get a clear `PERMISSION_DENIED` error in the next release. We might extend this further to make it more explicit which command got the permission denied error but for now, I’m closing this issue.

**Closed by cocreature** 2020-03-31 11:09 UTC
