### ISSUE TITLE
Migrating Sandbox from 0.13.55 to 1.1.1 failed with duplicated key error

### ISSUE THREAD

**Issue by lima-da** [digital-asset/daml#6017] opened 2020-05-19 00:39 UTC
Tried migrate an existing 0.13.55 sandbox with postgres database to sandbox-classic 1.1.1, got the following error:

```
2020-05-18 13:45:13.682 ERROR com.daml.resources.ProgramResource - Shutting down because of an initialization error.
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: SQL State  : 23505
Error Code : 0
Message    : ERROR: duplicate key value violates unique constraint "participant_contracts_create_key_hash_idx"
  Detail: Key (create_key_hash)=(\x87c92ed86797150f80a00f2b6530b623589e96029e2c1375eaccf0b58c7bc6e8) already exists.

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:372)
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:282)
	at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:279)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:71)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:94)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:193)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:153)
	at org.flywaydb.core.Flyway.execute(Flyway.java:521)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:153)
	at com.daml.platform.store.FlywayMigrations.$anonfun$migrate$2(FlywayMigrations.scala:45)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at com.daml.dec.DirectExecutionContext$.execute(DirectExecutionContext.scala:16)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:372)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:371)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:379)
	at scala.concurrent.impl.Promise.transform(Promise.scala:33)
	at scala.concurrent.impl.Promise.transform$(Promise.scala:31)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:379)
	at scala.concurrent.Future.map(Future.scala:292)
	at scala.concurrent.Future.map$(Future.scala:292)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:379)
	at scala.concurrent.Future$.apply(Future.scala:659)
	at com.daml.platform.store.FlywayMigrations.$anonfun$migrate$1(FlywayMigrations.scala:38)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at com.daml.dec.DirectExecutionContext$.execute(DirectExecutionContext.scala:16)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallback(Promise.scala:316)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:307)
	at scala.concurrent.impl.Promise.transformWith(Promise.scala:40)
	at scala.concurrent.impl.Promise.transformWith$(Promise.scala:38)
	at scala.concurrent.impl.Promise$DefaultPromise.transformWith(Promise.scala:187)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)
	at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:187)
	at com.daml.resources.ResourceOwner.use(ResourceOwner.scala:61)
	at com.daml.resources.ResourceOwner.use$(ResourceOwner.scala:58)
	at com.daml.resources.CloseableResourceOwner.use(CloseableResourceOwner.scala:8)
	at com.daml.platform.store.FlywayMigrations.migrate(FlywayMigrations.scala:37)
	at com.daml.platform.sandbox.stores.ledger.sql.SqlLedger$.$anonfun$owner$1(SqlLedger.scala:64)
	at com.daml.resources.FutureResourceOwner.acquire(FutureResourceOwner.scala:10)
	at com.daml.resources.ResourceOwner$$anon$2.acquire(ResourceOwner.scala:40)
	at com.daml.resources.ResourceOwner$$anon$2.acquire(ResourceOwner.scala:40)
	at com.daml.platform.sandbox.SandboxServer.buildAndStartApiServer(SandboxServer.scala:252)
	at com.daml.platform.sandbox.SandboxServer.$anonfun$start$1(SandboxServer.scala:329)
	at com.daml.logging.LoggingContext$.withEnrichedLoggingContext(LoggingContext.scala:23)
	at com.daml.logging.LoggingContext$.$anonfun$newLoggingContext$1(LoggingContext.scala:19)
	at com.daml.logging.LoggingContext$.newLoggingContext(LoggingContext.scala:15)
	at com.daml.logging.LoggingContext$.newLoggingContext(LoggingContext.scala:19)
	at com.daml.platform.sandbox.SandboxServer.start(SandboxServer.scala:327)
	at com.daml.platform.sandbox.SandboxServer.<init>(SandboxServer.scala:162)
	at com.daml.platform.sandbox.SandboxServer$.$anonfun$owner$7(SandboxServer.scala:69)
	at scala.util.Try$.apply(Try.scala:213)
	at com.daml.platform.sandbox.SandboxServer$.$anonfun$owner$6(SandboxServer.scala:69)
	at com.daml.resources.ResourceOwner$.$anonfun$forTryCloseable$1(ResourceOwner.scala:98)
	at com.daml.resources.FutureCloseableResourceOwner.acquire(FutureCloseableResourceOwner.scala:11)
	at com.daml.resources.ResourceOwner$$anon$2.acquire(ResourceOwner.scala:40)
	at com.daml.resources.ResourceOwner$$anon$2.$anonfun$acquire$1(ResourceOwner.scala:40)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.BatchUpdateException: Batch entry 14 update participant_contracts set create_key_hash = ? where contract_id = '#43:7' was aborted: ERROR: duplicate key value violates unique constraint "participant_contracts_create_key_hash_idx"
  Detail: Key (create_key_hash)=(\x87c92ed86797150f80a00f2b6530b623589e96029e2c1375eaccf0b58c7bc6e8) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:153)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2242)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:508)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:850)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:873)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1562)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at db.migration.postgres.V28__Fix_key_hashes.migrate(V28__Fix_key_hashes.scala:43)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:48)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:366)
	... 84 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "participant_contracts_create_key_hash_idx"
  Detail: Key (create_key_hash)=(\x87c92ed86797150f80a00f2b6530b623589e96029e2c1375eaccf0b58c7bc6e8) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	... 93 common frames omitted
```

**Comment by stefanobaghino-da** [comment] 2020-05-20 17:19
The issue is the same as #5659. We fixed the broken V25 in V29 but failed to check whether the broken V25 had effects on migrations 26, 27 and 28. We'll reserve time next week to fix this. Thanks for reporting.

**Comment by stefanobaghino-da** [comment] 2020-05-26 13:56
I conducted a small investigation of the other migrations happening between v25 and v29.

To recap:
- the new schema to serve the transaction and active contract services stores individual events
- events are either creates or exercise, with creates being served by both services backed by this table
- in order for the active contracts to be queried efficiently from this table, a column keeps track of the offset at which the contract created a create event has been consumed by a corresponding exercise events (see [normal execution states](#appendix-a1-normal-execution-states))
- migration v25 aimed at backfilling events in the new schema using transactions from the old one -- in doing so, the transaction were mistakenly not read in chronological order from the old schema: by reading an exercise event _before_ the corresponding create event was there, the `create_consumed_at` column could not be updated and was subsequently simply set to null when the create is read (_after_ the exercise has been processed already -- see [V25 execution states](#appendix-a2-v25-execution-states))
- migration V29 solved the issue at the point above by dropping the table completely and re-applying the same process but without foregoing the necessary ordering
- since migrations are applied strictly in version order, this means however that migrations V26, V27 and V28 still saw the database in a state which was possibly inconsistent

To dive into the migrations occurring between V25 and V29:
- V26 create the new schema for live contract data (used for DAML execution and validation, not to serve items via the Ledger API) and does not rely on `participant_events`, so it's not affected by the inconsistency introduced by V25
- _however_ V26 introduced an issue itself: the migration mistakenly imported into the new schema data for _all_ contracts, including the archived ones -- however, the migration filled up the keys from a table that did _not_ contain data about archived contracts, hiding the error by not causing duplicate unique key errors
- V27 updates `participant_events` by removing the unnecessary `is_root` column and merging `template_package_id` and `template_name` into a single `template_id` column -- this change is not affected by the inconsistent state of `create_consumed_at`
- V28 aims at recomputing the hash of contract keys for `participant_contracts` (up until that point we were mistakenly using a deprecated method): since `participant_contracts` does not store the contract key but only it's hash (to perform lookup-by-key operations), we had to fetch it from the `participant_events` table and filter for active contracts, as identified by having a non-null `create_consumed_at`; coupled with the inconsistent state left by V25 and V26, this causes an error in the situation in which two contracts would end up sharing the same contract key, which the index database rejects (see (V28 broken state)[#appendix-b-v28-broken-state]).

## Short-term solution

In order to fix the existing issue, we will do the following:
- a new migration V32.0 will be introduced to fix the contracts table 
- the existing V28 migration will be changed in place to do nothing
- the code for V28 will be re-introduced as V32.1, after V29 has solved the inconsistency
- this is possible because there is no checksum happening for migrations written in Java (like V28)
- this means that the migration equivalent to V28 will be applied a second-time by whomever was able to go through V28 without hitting the bug
- this means extra unnecessary migration time but the operation is safe to be performed

## Long-term improvements

Possible improvements up for discussion to make sure the migration is reliable in future versions:

- establish a framework around migrations that allows to perform migrations at a higher level of abstraction rather than directly accessing the index database without any check -- focusing on correctness-by-construction should be favored over testing
- regardless of the need to favor correctness-by-construction, establish an extensive set of integration tests to increase confidence in the correctness of the migrations, harnessing some known state and performing migrations
- the above can possibly be greatly improved by having internal customers (and possibly even community builds) on-board to have builds based on the latest master, ensuring us to catch bugs early
- to facilitate spotting and fixing issues, group together migrations pertaining to the migration to an SDK version to facilitate locating issues (either by squashing on a per-release basis or adopting a different naming convention for migration versions)

## Appendixes

### Appendix A1: Normal execution states

The following is a series of (simplified) states the events table will be in as DAML transactions are evaluated, persisted and finally indexed on the local participant:

1. a contract is created at offset 1

| offset | contract_id | create_arg | consumed_at | exercise_arg | consuming |
|--------|-------------|-----------------|--------------------|-------------------|-----------|
| 1      | 42          | foo             | null               | null              | null      |

2. a non-consuming event does not cause `create_consumed_at` to change at offset 1

| offset | contract_id | create_arg | consumed_at | exercise_arg | consuming |
|--------|-------------|-----------------|--------------------|-------------------|-----------|
| 1      | 42          | foo             | null               | null              | null      |
| 2      | 42          | null            | null               | bar               | false     |

3. a consuming event triggers `create_consumed_at` to be updated with the offset at which the consuming event occurred

| offset | contract_id | create_arg | consumed_at | exercise_arg | consuming |
|--------|-------------|-----------------|--------------------|-------------------|-----------|
| 1      | 42          | foo             | 3                  | null              | null      |
| 2      | 42          | null            | null               | bar               | false     |
| 3      | 42          | null            | null               | baz               | true      |

### Appendix A2: V25 execution states

1. while reading transactions from the old schema, transactions at offsets 2 and 3 are mistakenly read _before_ the corresponding create is (`create_consumed_at` cannot be updated simply because it's not there) and the resulting events are persisted

| offset | contract_id | create_arg | consumed_at | exercise_arg | consuming |
|--------|-------------|-----------------|--------------------|-------------------|-----------|
| 2      | 42          | null            | null               | bar               | false     |
| 3      | 42          | null            | null               | baz               | true      |

2. the create at offset 1 is added with `create_consumed_at` set to null (it's initial state) without the possibility of it ever going to be correctly updated, leaving the index database in an inconsistent state

| offset | contract_id | create_arg | consumed_at | exercise_arg | consuming |
|--------|-------------|-----------------|--------------------|-------------------|-----------|
| 2      | 42          | null            | null               | bar               | false     |
| 3      | 42          | null            | null               | baz               | true      |
| 1      | 42          | foo             | null               | null              | null      |

### Appendix B: V28 broken state

a. the events table incorrectly has `create_consumed_at` equal to `null` at offset 1 due to the bug in V25

| offset | contract_id | create_arg | create_key | consumed_at | exercise_consuming |
|--------|-------------|------------|------------|-------------|--------------------|
| 2      | 42          | null       | null       | null        | true               |
| 2      | 43          | arg2       | key1       | null        | null               |
| 1      | 42          | arg1       | key1       | null        | null               |

b. the contracts table incorrectly has both the contracts, despite 42 being archived -- note that 42 does not have a key because the previous migration did not contain data for keys of archived contracts

| contract_id | create_key_hash |
|-------------|-----------------|
| 42          | null            |
| 43          | key1_hash       |

c. V28 selects all `create_key`s with a null `create_consumed_at`, hashes it and updates `create_key_hash` in the contracts table

d. both 42 and 43 are updated to have the same key hash (because they had the same key on the events table and 42 was erroneously reported as active), triggering the duplicate unique key error

**Closed** 2020-05-27 06:37 UTC
Labels: component/ledger
