### ISSUE TITLE
Please add codegen support for `createAndExercise` choice on daml template

### ISSUE THREAD

**Issue by petro-semeniuk-da** [digital-asset/daml#1092] opened 2019-05-13 07:36 UTC
Almost all our ledger interactions are via choices however genesis is done non-atomically and having atomic way via `createAndExercise` would be great.

**Comment by bitonic** [comment] 2019-05-14 09:38
@S11001001 or @leo-da : could you take care of this for scala?

**Comment by leo-da** [comment] 2019-05-21 13:41
@S11001001: Can we close this issue? Do we need anything else to support `CreateAndExercise` in scala codegen?

**Comment by petro-semeniuk-da** [comment] 2019-05-22 06:58
Hey Leo, we are about to upgrade to 0.12.8 and pickup this goodness.

Are you able to wait for few more days?

**Comment by bitonic** [comment] 2019-05-22 08:02
@petro-semeniuk-da , the issue is fixed in master, so I'll close. please let us know if 0.12.18 works for you, and create / reopen an issue if necessary.

**Closed by bitonic** 2019-05-22 08:02 UTC
Labels: component/java-ecosystem, component/scala-ecosystem
