### ISSUE TITLE
Report missing Parties.

### ISSUE THREAD

**Issue by leonidr-da** [digital-asset/daml#14402] opened 2022-07-13 00:46 UTC
When we send a request to process a payload, we sometimes send it without first allocating a party. This results in
```
ExecutionException while processing the event in processElement method. java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: MULTI_DOMAIN_SUPPORT_NOT_ENABLED(9,d03a3c81): This transaction requires multi-domain support which is turned off on this participant
```
Could we add more information to that response so that it is broken apart and
1. is explicit about the missing parties
2. tell which parties are missing?

### What is the problem you want to solve?

Clearer error message.

### What is the solution you would propose?

New error code.

### Describe alternatives you've considered

N/A 

### Additional context

N/A

**Comment by daravep** [comment] 2022-07-13 12:44
duplicate of https://github.com/DACH-NY/canton/issues/9570

**Comment by cocreature** [comment] 2022-07-13 12:59
closing as a duplicate

**Closed by cocreature** 2022-07-13 12:59 UTC
