### ISSUE TITLE
Remove support for LF 1.0 

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#18240] opened 2024-01-22 12:25 UTC
- [ ] cleanup proto (lf, transaction)
- [ ] cleanup spec (lf, value, transaction)

**Comment by paulbrauner-da** [comment] 2024-02-14 12:11
Duplicate of https://github.com/digital-asset/daml/issues/18457

**Closed** 2024-02-14 12:12 UTC
