### ISSUE TITLE
DAML compiler can give false positives for 'unused bindings'

### ISSUE THREAD

**Issue by tamaskalcza-da** [digital-asset/daml#5878] opened 2020-05-06 20:05 UTC
Given that the _unused bindings_ setting is turned on in `daml.yaml` the compiler can give false-positive results.
```yaml
build-options:
  - '--ghc-option'
  - '-Werror'
  - '--ghc-option'
  - '-Wunused-binds'
```

In the example below `allParties` is being used multiple times and yet the compiler gives the error:
`Defined but not used: ‘allParties’`

```haskell
template Example
  with
    a : Party
    b : Party
  where
    let allParties = [a, b]
    signatory a
    observer allParties

    controller allParties can
      Sample: () do pure ()
```

**Comment by cocreature** [comment] 2020-05-07 04:18
This is a duplicate of https://github.com/digital-asset/daml/issues/2611. The way we desugar templates currently produces a bunch of bindings regardless of whether they are used or not, e.g., here you’ll get a binding for the signatories which do not use `allParties`.

This is fixable but somewhat tedious so it never got prioritized so far.

**Closed by cocreature** 2020-05-07 04:18 UTC
