### ISSUE TITLE
bazel build //... fails on node_nix repo

### ISSUE THREAD

**Issue by heath-hh** [digital-asset/daml#3407] opened 2019-11-09 21:08 UTC
bazel build for macOS Catalina 10.15 fails as follows:

```$ bazel build //...
INFO: Invocation ID: 392d2285-9a20-4c8c-8341-c69a8413c864
INFO: Call stack for the definition of repository 'node_nix' which is a _nixpkgs_package (rule definition at /private/var/tmp/_bazel_heath/3f268698d87b95a1cad98f3145b077d9/external/io_tweag_rules_nixpkgs/nixpkgs/nixpkgs.bzl:253:20):
 - /private/var/tmp/_bazel_heath/3f268698d87b95a1cad98f3145b077d9/external/io_tweag_rules_nixpkgs/nixpkgs/nixpkgs.bzl:280:9
 - /Users/heath/dev/hh/sandbox/ssx/daml/WORKSPACE:338:1
ERROR: An error occurred during the fetch of repository 'node_nix':


Non hermetic configuration for repository node_nix.

The following dependencies are not declared in *nixpkgs_package* attributes.

You need to update the repository rule *node_nix* and set/extend *nix_file_deps* with the following dependencies (adapted to your workspace):

nix_file_deps = [
    "/System/Volumes/Data/opt/nix/store/6639l9815ggdnb4aka22qcjy7p8w4hb9-nix-2.3.1/share/nix/corepkgs/derivation.nix",
    "/System/Volumes/Data/opt/nix/store/6639l9815ggdnb4aka22qcjy7p8w4hb9-nix-2.3.1/share/nix/corepkgs/fetchurl.nix",
]

ERROR: error loading package '': Encountered error while reading extension file 'install_bazel_dependencies.bzl': no such package '@npm//': no such package '@nodejs//': no such package '@nodejs_dev_env//': no such package '@node_nix//':

Non hermetic configuration for repository node_nix.

The following dependencies are not declared in *nixpkgs_package* attributes.

You need to update the repository rule *node_nix* and set/extend *nix_file_deps* with the following dependencies (adapted to your workspace):

nix_file_deps = [
    "/System/Volumes/Data/opt/nix/store/6639l9815ggdnb4aka22qcjy7p8w4hb9-nix-2.3.1/share/nix/corepkgs/derivation.nix",
    "/System/Volumes/Data/opt/nix/store/6639l9815ggdnb4aka22qcjy7p8w4hb9-nix-2.3.1/share/nix/corepkgs/fetchurl.nix",
]

ERROR: error loading package '': Encountered error while reading extension file 'install_bazel_dependencies.bzl': no such package '@npm//': no such package '@nodejs//': no such package '@nodejs_dev_env//': no such package '@node_nix//':

Non hermetic configuration for repository node_nix.

The following dependencies are not declared in *nixpkgs_package* attributes.

You need to update the repository rule *node_nix* and set/extend *nix_file_deps* with the following dependencies (adapted to your workspace):

nix_file_deps = [
    "/System/Volumes/Data/opt/nix/store/6639l9815ggdnb4aka22qcjy7p8w4hb9-nix-2.3.1/share/nix/corepkgs/derivation.nix",
    "/System/Volumes/Data/opt/nix/store/6639l9815ggdnb4aka22qcjy7p8w4hb9-nix-2.3.1/share/nix/corepkgs/fetchurl.nix",
]

INFO: Elapsed time: 0.700s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @npm; Restarting.
    Fetching @nodejs; Restarting.
    Fetching @nodejs_dev_env; Restarting.```

**Comment by cocreature** [comment] 2019-11-10 17:21
Nix on MacOS can be a bit flaky. Try running `nix-build -A tools -A cached nix` as described in the readme until it succeeds and then run the Bazel command again. I also recall that Nix on Catalina has quite a few issues, e.g., https://github.com/NixOS/nix/issues/2925 but I’m not too familiar with the details there and haven’t tried it out myself.

**Comment by cocreature** [comment] 2019-11-11 11:42
It looks like this particular error was caused by your nix installation not being in `/nix`. We have merged an upgrade of `rules_nixpkgs` which might help with that. If it doesn’t, @SamirTalwar has managed to install nix in `/nix` on catalina somehow and can probably help you achive the same.

**Comment by SamirTalwar** [comment] 2019-11-11 13:27
I mostly just followed the instructions laid out by others in https://github.com/NixOS/nix/issues/2925, predominantly https://github.com/NixOS/nix/issues/2925#issuecomment-522482497 and https://github.com/NixOS/nix/issues/2925#issuecomment-522588455.

My memory is a bit fuzzy, but I think it was something like this:

1. Add a line containing `nix` to _/etc/synthetic.conf` (and create the file if it doesn't exist).
2. Reboot.

**Comment by SamirTalwar** [comment] 2019-11-11 13:27
Arg, too many keyboard shortcuts close to each other.

**Comment by SamirTalwar** [comment] 2019-11-11 13:29
I mostly just followed the instructions laid out by others in https://github.com/NixOS/nix/issues/2925, predominantly https://github.com/NixOS/nix/issues/2925#issuecomment-539570232. I believe I had no further issues after that.

**Comment by SamirTalwar** [comment] 2019-11-25 16:10
Any luck, @heath-hh?

**Comment by circlespainter** [comment] 2020-01-09 23:18
I've had the same problem with Ubuntu 18.04 but, rather than `nix-build -A tools -A cached nix`, I just `./build.sh` until everything got downloaded (several times).

**Comment by cocreature** [comment] 2020-07-17 14:49
I don’t think there is much we can do here so closing. feel free to reopen if you disagree.

**Closed by cocreature** 2020-07-17 14:49 UTC
