### ISSUE TITLE
`daml start` doesn't start the JSON API in environment without browser

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#5369] opened 2020-04-02 11:34 UTC
In a shell-only Ubuntu environment without a browser installed, I get the below output from  `daml start`, and the JSON API doesn't start. The obvious workaround is `daml start --open-browser no`, which does fix the issue, but it would be nicer to have an automatic fallback.

```
$ daml start
Compiling qs to a DAR.
Created .daml/dist/qs-0.0.1.dar
Waiting for sandbox to start:
INFO: Slf4jLogger started
INFO: DAML LF Engine supports LF versions: 0, 0.dev, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8,1.dev; Transaction versions: 1, 2, 3, 4, 5, 6, 7, 8, 9; Value versions: 1, 2, 3, 4, 5, 6, 7 (context: {participantId=sandbox-participant})
INFO: Listening on localhost:6865 over plain text. (context: {participantId=sandbox-participant})
   ____             ____
  / __/__ ____  ___/ / /  ___ __ __
 _\ \/ _ `/ _ \/ _  / _ \/ _ \\ \ /
/___/\_,_/_//_/\_,_/_.__/\___/_\_\

INFO: Initialized sandbox version 100.13.55 with ledger-id = sandbox-649e6026-78ec-44b1-bee9-9c5983c1969c, port = 6865, dar file = List(.daml/dist/qs-0.0.1.dar), time mode = static time, ledger =in-memory, auth-service = AuthServiceWildcard$, contract ids seeding = no
Waiting for navigator to start:
   _  __          _           __
  / |/ /__ __  __(_)__ ____ _/ /____  ____
 /    / _ `/ |/ / / _ `/ _ `/ __/ _ \/ __/
/_/|_/\_,_/|___/_/\_, /\_,_/\__/\___/_/
                 /___/
Version 100.13.55
Frontend running at http://localhost:7500.
Slf4jLogger started
INFO: Registered tracker for submitter Key(Script Runner,Alice) (context: {participantId=sandbox-participant})
INFO: Registered tracker for submitter Key(Script Runner,Bob) (context: {participantId=sandbox-participant})
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :1
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :1
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :1
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: chromium-browser: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: google-chrome: not found
```

**Comment by sofiafaro-da** [comment] 2020-11-16 15:14
It looks like this has been fixed. I tried to reproduce it in a headless ubuntu VM. After failing to open the browser, `daml start` goes ahead and starts the JSON API anyway. Can you still reproduce this error in SDK 1.7.0, @bame-da?

**Comment by sofiafaro-da** [comment] 2020-11-19 12:41
Closing for now until somebody can reproduce this in the current SDK.

**Closed by sofiafaro-da** 2020-11-19 12:41 UTC
Labels: language
