### ISSUE TITLE
Overwhelming messages when stopping sandbox.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#1431] opened 2019-05-28 14:06 UTC
In recent SDK versions, stopping the sandbox with Ctrl+C results in a ton of messages (see below), whether it's running through `daml start`, `daml sandbox` or `da run sandbox`. Could you suppress these, or make them go away?

cc @bitonic @gaboraranyossy-da @gerolf-da @rautenrieth-da 

Before Ctrl+C:

```
DAML LF Engine supports LF versions: 0, 0.dev, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.dev; Transaction versions: 1, 2, 3, 4, 5, 6, 7; Value versions: 1, 2, 3, 4
Starting plainText server
listening on localhost:6865
   ____             ____
  / __/__ ____  ___/ / /  ___ __ __
 _\ \/ _ `/ _ \/ _  / _ \/ _ \\ \ /
/___/\_,_/_//_/\_,_/_.__/\___/_\_\

Initialized sandbox version 100.12.21 with ledger-id = sandbox-97f5605c-dadf-4614-8840-0220b630c7b2, port = 6865, dar file = DamlPackageContainer(List(target/daml/iou.dar)), time mode = Static, ledger = in-memory, daml-engine = {}
```

After Ctrl+C: 

```
^CShutting down Command Service
Shutting down 0 trackers
[INFO] [05/28/2019 15:58:11.687] [sandbox-akka.actor.default-dispatcher-16] [akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-0] Message [com.digitalasset.grpc.adapter.RunnableSequencingActor$ShutdownRequest$] without sender to Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-0#-944269587] was not delivered. [1] dead letters encountered. If this is not an expected behavior, then [Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-0#-944269587]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [05/28/2019 15:58:11.688] [sandbox-akka.actor.default-dispatcher-12] [akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-1] Message [com.digitalasset.grpc.adapter.RunnableSequencingActor$ShutdownRequest$] without sender to Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-1#-1924083356] was not delivered. [2] dead letters encountered. If this is not an expected behavior, then [Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-1#-1924083356]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [05/28/2019 15:58:11.689] [sandbox-akka.actor.default-dispatcher-10] [akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-2] Message [com.digitalasset.grpc.adapter.RunnableSequencingActor$ShutdownRequest$] without sender to Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-2#-333723329] was not delivered. [3] dead letters encountered. If this is not an expected behavior, then [Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-2#-333723329]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [05/28/2019 15:58:11.689] [sandbox-akka.actor.default-dispatcher-10] [akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-3] Message [com.digitalasset.grpc.adapter.RunnableSequencingActor$ShutdownRequest$] without sender to Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-3#-1252264575] was not delivered. [4] dead letters encountered. If this is not an expected behavior, then [Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-3#-1252264575]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [05/28/2019 15:58:11.689] [sandbox-akka.actor.default-dispatcher-10] [akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-4] Message [com.digitalasset.grpc.adapter.RunnableSequencingActor$ShutdownRequest$] without sender to Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-4#66008952] was not delivered. [5] dead letters encountered. If this is not an expected behavior, then [Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-4#66008952]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [05/28/2019 15:58:11.689] [sandbox-akka.actor.default-dispatcher-8] [akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-5] Message [com.digitalasset.grpc.adapter.RunnableSequencingActor$ShutdownRequest$] without sender to Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-5#2066521169] was not delivered. [6] dead letters encountered. If this is not an expected behavior, then [Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-5#2066521169]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [05/28/2019 15:58:11.689] [sandbox-akka.actor.default-dispatcher-8] [akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-6] Message [com.digitalasset.grpc.adapter.RunnableSequencingActor$ShutdownRequest$] without sender to Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-6#-1787123739] was not delivered. [7] dead letters encountered. If this is not an expected behavior, then [Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-6#-1787123739]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [05/28/2019 15:58:11.693] [sandbox-akka.actor.default-dispatcher-8] [akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-7] Message [com.digitalasset.grpc.adapter.RunnableSequencingActor$ShutdownRequest$] without sender to Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-7#-148304014] was not delivered. [8] dead letters encountered. If this is not an expected behavior, then [Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-7#-148304014]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [05/28/2019 15:58:11.694] [sandbox-akka.actor.default-dispatcher-8] [akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-8] Message [com.digitalasset.grpc.adapter.RunnableSequencingActor$ShutdownRequest$] without sender to Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-8#-574784568] was not delivered. [9] dead letters encountered. If this is not an expected behavior, then [Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-8#-574784568]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [05/28/2019 15:58:11.694] [sandbox-akka.actor.default-dispatcher-8] [akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-9] Message [com.digitalasset.grpc.adapter.RunnableSequencingActor$ShutdownRequest$] without sender to Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-9#-1074386551] was not delivered. [10] dead letters encountered, no more dead letters will be logged. If this is not an expected behavior, then [Actor[akka://sandbox/user/ledger-api-server-rs-grpc-bridge-505c850b-25b9-40fc-ae9a-44a9b6924744-9#-1074386551]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

These *long lines* take up the whole terminal screen.

**Comment by gerolf-da** [comment] 2019-08-09 12:07
Duplicate of https://github.com/digital-asset/daml/issues/1886, which is fixed in master.

**Closed by gerolf-da** 2019-08-09 12:07 UTC
Labels: component/ledger
