### ISSUE TITLE
Cannot name a choice argument as arg: conflicting definitions

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#7805] opened 2020-10-26 08:43 UTC
This template causes a compile error.
```
module Mwe where
template CompileError
  with
    party : Party
  where
    signatory party
    controller party can
      Call : ()
        with
          arg: Int
        do
          pure ()
```
causes: 
```
  daml/Mwe.daml:11:9: error:
  • Conflicting definitions for ‘arg’
  Bound at: daml/Mwe.daml:(11,9)-(12,17)
  <no location info>
  • In a lambda abstraction
```

Renaming `arg` to e.g. `argt` resolves the issue.
Apparently `arg` is like a reserved word, but the docs don't mention it:
https://docs.daml.com/daml/reference/choices.html#choice-arguments

**Comment by cocreature** [comment] 2020-10-26 09:00
Closing as duplicate of #3017

**Closed by cocreature** 2020-10-26 09:00 UTC
Labels: language
