### ISSUE TITLE
Sandbox exhibits high CPU/memory usage after a while in wall-clock mode

### ISSUE THREAD

**Issue by da-tanabe** [digital-asset/daml#1320] opened 2019-05-22 16:50 UTC
It's not easy to reproduce in a short period of time, but after leaving the Sandbox open with wall-clock mode for a day or so, CPU usage suddenly seems to spike.

In trying to come up with a better repro scenario, I tried:
* Dramatically increasing the heartbeat rate (in https://github.com/digital-asset/daml/blob/master/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/SandboxServer.scala#L58, change to `10.milliseconds`)
* Repeatedly reading the full transaction stream over and over again (I use `dazl` but I suspect doing something like opening and closing Navigator repeatedly would accomplish a similar effect)

Not sure if this is one issue or two.

**Comment by da-tanabe** [comment] 2019-05-31 14:40
Ok—we came up with a workaround that might point to the underlying issue.

After leaving the Sandbox running for a longish time (24 hours), recycling all the connections from the database side seems to make the Sandbox a lot happier:

https://stackoverflow.com/questions/5408156/how-to-drop-a-postgresql-database-if-there-are-active-connections-to-it

After dropping all connections, Sandbox spent about a minute gathering its thoughts, and afterwards CPU dropped back down to nothing, and it was able to service connections (take commands, return transactions) normally again.

**Comment by gerolf-da** [comment] 2019-06-07 12:56
So far I was NOT able to reproduce with the `sandbox-binary` with the following scenarios with Postgres backend and wall-clock time:

1) Simply letting the sandbox run for 24hours with no activity
1) Having an application do the following loop continuously:
    1) read active contracts
    1) archive all contracts
    1) create 1000 new contracts

**Comment by stefanobaghino-da** [comment] 2020-06-05 09:37
@da-tanabe is this still the case? Any chance you can test this again?

**Comment by stefanobaghino-da** [comment] 2020-07-17 11:20
No feedback, closing.

**Closed by stefanobaghino-da** 2020-07-17 11:20 UTC
Labels: component/ledger
