### ISSUE TITLE
Specifying --project-root overrides the version set in a daml.yaml file

### ISSUE THREAD

**Issue by da-tanabe** [digital-asset/daml#5769] opened 2020-04-28 18:26 UTC
Specifying `--project-root` overrides the version set in a daml.yaml file while also printing out an incorrect and misleading warning message.

Steps to repro:

```console
$ DAML_SDK_VERSION=0.13.55 daml new quickstart-0.13.55
Created a new project in "quickstart-0.13.55" based on the template "skeleton".
$ daml build --project-root quickstart-0.13.55
Warning: Using DAML SDK version 1.0.1 from DAML_SDK_VERSION enviroment variable instead of DAML SDK version 0.13.55 from daml.yaml config file.
Warning: Using DAML SDK version 1.0.1 from DAML_SDK_VERSION enviroment variable instead of DAML SDK version 0.13.55 from daml.yaml config file.
Warning: Using DAML SDK version 1.0.1 from DAML_SDK_VERSION enviroment variable instead of DAML SDK version 0.13.55 from daml.yaml config file.
$ cd quickstart-0.13.55
Compiling quickstart-0.13.55 to a DAR.
Created .daml/dist/quickstart-0.13.55-0.0.1.dar
$ daml build
DAML SDK 1.0.1 has been released!
See https://github.com/digital-asset/daml/releases/tag/v1.0.1 for details.

Compiling quickstart-0.13.55 to a DAR.
Created .daml/dist/quickstart-0.13.55-0.0.1.dar
```

The warning in the first instance is also wrong, as I do not have the `DAML_SDK_VERSION` environment variable set at all (as evidenced by proper behavior when I simply `cd` into a directory that contains a `daml.yaml` file).

Additionally, running `DAML_SDK_VERSION=0.13.55 daml build --project-root quickstart-0.13.55` appears to still do the correct thing.

**Comment by cocreature** [comment] 2020-04-29 11:27
I’m not really sure what we could do about this one. What is happening is the following:
1. The assistant determines your SDK version. You are outside of a project so it uses what `DAML_SDK_VERSION` is set to or if that is not set, the latest SDK version you have installed.
2. It then calls `damlc` of that SDK version with `DAML_SDK_VERSION` set to that version.
3. `damlc` passes the `--project-root` option and goes to that directory parses the `daml.yaml` and sees that the SDK version there is different from the one the assistant has passed to it and emits the warning.

So the problem is that at the point where we parse `daml.yaml` we are already in `damlc` and cannot switch the SDK version. What you can do I believe is to set `DAML_PROJECT` instead of using `--project-root`. That will be resolved by the assistant so it should select the correct version. I haven’t actually tried it out so if it doesn’t work let me know.

**Comment by da-tanabe** [comment] 2020-04-29 20:10
It's not a blocking problem for me (I just simply `cd` into the directory with `daml.yaml` in it now), but the behavior is definitely unexpected and at the very least, the error message isn't true from the user's perspective (because the user doesn't set `DAML_SDK_VERSION`).

Maybe `--project-root` should move to an arg of `daml` itself? (a.k.a. `daml --project-root BLAH build`), and the `daml build --project-root` flag be deprecated?

**Comment by cocreature** [comment] 2020-05-05 09:16
The docs for `--project-root` now point to `DAML_PROJECT`. I think that’s the best we can do here for now so closing this.

**Closed by cocreature** 2020-05-05 09:16 UTC
Labels: language, language/now
