### ISSUE TITLE
Scenarios are still part of the `Writing Daml` section of the docs

### ISSUE THREAD

**Issue by nemanja-da** [digital-asset/daml#9330] opened 2021-04-06 15:13 UTC
As far as I understood we're deprecating `scenarios` in favor of Daml Script. Scenarios are still referenced in the docs as the  [favorable way of testing](https://docs.daml.com/daml/testing-scenarios.html)

**Comment by cocreature** [comment] 2021-04-06 15:43
duplicate of #8839

**Closed by cocreature** 2021-04-06 15:43 UTC
