### ISSUE TITLE
make the ACS only publish stakeholder contracts

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#164] opened 2019-04-01 14:04 UTC
we've had some discussions about what events to expose on the ACS, and reached the following conclusion:

* we will stop producing events regarding contracts that none of the requesting parties is a stakeholder of in the ACS and in the flat transaction stream. Motivation: we want the ACS size to not grow indefinitely and we do not want applications to rely on events generated because of transaction witnesses to know about contracts. In general, if you are designing a DAML workflow and you want to know about a contract, you should create a contract with the data you're interested in and put yourself as a stakeholder of said contract. Moreover removing these events from the ACS only is not desirable because we want the common path of catching up with the ACS and then start consuming from the flat transaction stream to work nicely – it wouldn't if the flat transaction stream delivers different data from the ACS by default.
* we agreed that decorating events with "witnesses" as we're doing now is not ideal, and we'd like to adopt a more explicit route of just decorating them with signatories and observers instead. Note that if you have the stakeholders and you want to re-compute the witnesses you can do so with the transaction trees, but we think that for most application the most sensible data to expose is the stakeholder information, not the witness information. Also note that currently you cannot know who the stakeholders of a contract are from the ledger api, both because the witnesses are a superset of the stakeholders and because the witnesses must necessarily be restricted to the subscribing parties to avoid privacy leaks. This proposal would address this shortcoming, while not leaking information.

**Comment by da-tanabe** [comment] 2019-06-17 22:02
Running the scenario in this DAML file ends with `SentLetter` in Alice's Navigator view, despite not being a `Party` to that final contract:

https://gist.github.com/da-tanabe/ec0943a3d7f970d50c925191f800fe37

**Comment by gerolf-da** [comment] 2020-02-14 10:14
Closing this as duplicate of #3254

**Closed by gerolf-da** 2020-02-14 10:14 UTC
Labels: component/ledger
