### ISSUE TITLE
Duplicate "Not in scope" errors with missing location

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#15571] opened 2022-11-15 09:19 UTC
```
module Main where

import Daml.Script

template T
  with
    p : NonexistentType
  where
    signatory p
```

produces
```

2022-11-15 09:17:52.33 [INFO]  [build] 
Compiling foobar to a DAR.
File:     daml/Main.daml
Hidden:   no
Range:    1:1-1:1
Source:   typecheck
Severity: DsError
Message:  daml/Main.daml:1:1: error:Not in scope: type constructor or class ‘NonexistentType’
File:     daml/Main.daml
Hidden:   no
Range:    1:1-1:1
Source:   typecheck
Severity: DsError
Message:  daml/Main.daml:1:1: error:Not in scope: type constructor or class ‘NonexistentType’
File:     daml/Main.daml
Hidden:   no
Range:    1:1-1:1
Source:   typecheck
Severity: DsError
Message:  daml/Main.daml:1:1: error:Not in scope: type constructor or class ‘NonexistentType’
File:     daml/Main.daml
Hidden:   no
Range:    7:9-7:24
Source:   typecheck
Severity: DsError
Message:  daml/Main.daml:7:9: error:Not in scope: type constructor or class ‘NonexistentType’
ERROR: Creation of DAR file failed.
```

One of those is right, the other ones are duplicate artifacts of desugaring and are at least missing location info.

Tested on `2.5.0-snapshot.20221107.10906.0.346bb489` but afaict this is not new.

**Comment by akrmn** [comment] 2022-11-15 15:34
duplicate of https://github.com/digital-asset/daml/issues/13826, sorry @cocreature we'll get to it at some point 😞

**Comment by cocreature** [comment] 2022-11-15 15:35
duh sorry I had forgotten about that

**Closed by akrmn** 2022-11-15 15:34 UTC
