### ISSUE TITLE
//ledger/ledger-api-test-tool:ledger-api-test-tool-ssltest flaky on master

### ISSUE THREAD

**Issue by garyverhaegen-da** [digital-asset/daml#906] opened 2019-05-03 20:21 UTC
This seemingly unrelated [commit](https://github.com/digital-asset/daml/commit/0ebdcb961edfc0cae74fb1d92327e56d32918562) failed to [build](https://dev.azure.com/digitalasset/daml/_build/results?buildId=4299). Rerun passed so this is flaky. @gleber-da is this related to #815?

**Comment by gleber-da** [comment] 2019-05-06 08:24
It's a dupe of #815

**Closed by gleber-da** 2019-05-06 08:24 UTC
