### ISSUE TITLE
Sandbox server exits with a non-zero status code on normal termination.

### ISSUE THREAD

**Issue by SamirTalwar** [digital-asset/daml#4226] opened 2020-01-27 14:29 UTC
When running the Sandbox server on Linux or macOS (using e.g. `daml sandbox` or `bazel run //ledger/sandbox:sandbox-binary …`), pressing Ctrl+C or issuing a SIGTERM results in an exit status appropriate to the signal. For example, Ctrl+C (SIGINT) results in an exit status of 130 (128 + 2), and SIGTERM yields an exit status of 143 (128 + 15).

When the process terminates, it should probably exit with a status of 0 if it was terminated normally, or a status of 1 if it terminated due to abnormal reasons (i.e. a crash). This will make it much easier to detect an expected termination as opposed to an unexpected one, which is crucial when running the process in any kind of scheduler or orchestrator so that failure can be reported and handled.

**Comment by gerolf-da** [comment] 2020-02-14 10:41
Could you help me understand what the issue is? Right now we don't really have the notion of "normal termination", although a coordinated shutdown procedure would be a great feature to have.

**Comment by SamirTalwar-DA** [comment] 2020-02-14 10:51
When we stop the Sandbox server through "normal" means (i.e. SIGTERM), it effectively reports that it crashed by exiting with a non-zero status code. This can cause havoc with automated operations (e.g. Docker, Kubernetes, etc.) because it looks like the application crashed, which can make your monitoring useless because even controlled shutdowns will send alerts. Haven't tested this hypothesis though.

**Comment by SamirTalwar-DA** [comment] 2020-02-18 16:47
Got confirmation from our users at DABL that this doesn't currently affect them and they don't foresee a problem, so I'm closing this. We can re-open it if it becomes an issue.

**Closed by SamirTalwar-DA** 2020-02-18 16:47 UTC
