### ISSUE TITLE
Navigator is showing witnessed contracts

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#3006] opened 2019-09-24 16:28 UTC
Contracts whose creates are witnessed, but where the logged-in party is not a stakeholder are shown in Navigator. I think this is a regression. In any case, I don't think we should show witnessed contracts of any kind by default.

**Comment by gerolf-da** [comment] 2019-09-25 08:48
What do you mean by "witnessed"? The create node being part of a transaction tree that the party can see, but shouldn't see the create node?

**Comment by rautenrieth-da** [comment] 2019-09-25 08:55
Since we switched to the gRPC ledger API, Navigator has always displayed all contracts that it can see from the `GetTransactionTrees` stream.

If we have a regression where Navigator now displays more contracts, then it means the behavior of `GetTransactionTrees` has changed.

**Comment by bame-da** [comment] 2019-09-25 09:03
I must be misremembering. I thought we did something in the context of #164, but I see even that is still Open.

I don't think Transaction Stream, ACS, or Navigator should emit contracts that the party isn't a stakeholder to. It confuses and encourages poor DAML design.

**Comment by rautenrieth-da** [comment] 2019-09-25 11:05
> I don't think Transaction Stream, ACS, (...) should emit contracts that the party isn't a stakeholder to.

That's exactly the point of #164, no? I think of Navigator as a "powerful developer tool", so in general Navigator lets you see everything that is somehow visible over the ledger API. Apart from removing the non-stakeholder contracts from the ledger API, Navigator could add more filters to the UI, so that you can switch between stakeholder/all contracts (similar to how you can toggle the display of archived contracts).

**Comment by gerolf-da** [comment] 2019-09-25 11:20
> I don't think Transaction Stream, ACS, or Navigator should emit contracts that the party isn't a stakeholder to. It confuses and encourages poor DAML design.

By "TransactionStream" are you only referring to the flat transactions, or also the transaction trees?

**Comment by bame-da** [comment] 2019-09-25 11:59
I mean the flat stream. TransactionTree should include all events, including witnessed ones. It should also include divulged contracts, which it didn't last time I checked. I'm in favour of @rautenrieth-da 's idea of making both "witnessed" as well as "divulged" contracts available in Navigator in a fashion similar to "archived". But I think it should be opt-in, ie unchecked by default.

**Comment by gerolf-da** [comment] 2019-09-25 12:11
We haven't exposed divulged contracts over the ledger api up to now. In fact that is actually a very significant difference between disclosed contracts (visible over the ledger api) and divulged contracts (only available for validation of transactions).

**Comment by gerolf-da** [comment] 2019-09-25 12:16
Also, we don't expose create contracts for non-stakeholders already. The only reason you see them in navigator is because it is using the TransactionTree, where we indeed do include the created events also for the parent witnesses.

**Comment by cocreature** [comment] 2020-02-24 08:38
Can this be closed with #4594 merged?

**Comment by rautenrieth-da** [comment] 2020-02-27 09:53
Fixed by #4594.

**Closed by rautenrieth-da** 2020-02-27 09:53 UTC
Labels: component/navigator
