### ISSUE TITLE
With syntax does not play well with bad Haddock comment indentation

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#2188] opened 2019-07-17 11:27 UTC
```haskell
data Foo = Foo with
  bar : Int
  -- ^ some more docs

foo = Foo with bar = 5
```
fails to parse at `foo` with
```
data Foo = Foo with
  bar : Int
  -- ^ some more docs

foo = Foo with bar = 5
```

**Comment by cocreature** [comment] 2019-07-17 11:33
Duplicate of https://github.com/digital-asset/daml/issues/1141

**Closed by cocreature** 2019-07-17 11:33 UTC
Labels: language, language/next
