### ISSUE TITLE
Static Configuration for Trigger Service

### ISSUE THREAD

**Issue by darko-da** [digital-asset/daml#9287] opened 2021-03-30 14:39 UTC
It would to be able to provide a static configuration for the trigger service such that I can start it up already configured with certain triggers for certain parties.

Otherwise, I have to start it up, and then interact with the HTTP API to configure it properly.

**Comment by cocreature** [comment] 2021-03-30 14:43
duplicate of #9173

**Closed by cocreature** 2021-03-30 14:43 UTC
