### ISSUE TITLE
Can't import inside twice nested modules in Windows

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#1284] opened 2019-05-21 13:12 UTC
To replicate, in windows:

1. Create new project with `daml new p`
2. create a new module `A.B.C` and import main by creating `p/daml/A/B/C.daml` with
  ```
daml 1.2
module A.B.C where

import Main
   ```
3. Observe the error appearing on the import statement.

**Comment by cocreature** [comment] 2019-05-21 14:47
I expect that this is probably caused by the IDE using absolute file paths which mess with the module chaser in some way. It should be fixed once we finally get @DavidM-D’s PR merged. But we should probably also just fix the module chaser to behave properly in this case.

**Closed** 2019-07-01 13:20 UTC
Labels: language
