### ISSUE TITLE
WebIDE displays blank page when run through Safari / iOS

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#1286] opened 2019-05-21 13:44 UTC
When https://webide.daml.com is opened in Safari, after accepting the terms and conditions, the IDE itself displays as a blank page.

![image](https://user-images.githubusercontent.com/25179017/58101087-f2d2bf80-7bac-11e9-8dcc-0cafe86adefc.png)

When running the underlying code-server locally via docker, this does load correctly on Safari
![image](https://user-images.githubusercontent.com/25179017/58101112-0120db80-7bad-11e9-8244-7524f8592584.png)

Suspicion is this may be related to CSP settings for Safari

Issue also raised via twitter https://twitter.com/danielselman/status/1130740764525432832

**Comment by garyverhaegen-da** [comment] 2019-05-21 14:20
Looking at the CSP served, it does seem to be missing it:
```
content-security-policy: default-src 'self'; connect-src 'self' ws://webide.daml.com:80/; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;
```

Websockets are governed by the `connect-src` property; we're only authorizing connections to self (which goes through the `https` protocol and s thus irrelevant for websockets) and `ws://webide.daml.com:80/`, which does not present the correct protocol. I'm actually surprised this works in Chrome. Note that Chrome also presents a number of csp-related errors, though they do not seem to prevent the page from rendering.

@bolek-wisniewski for the Safari issue, I believe it should be enough to add `wss://webide.daml.com` to the `connect-src` property. The Chrome errors should probably be looked into too, at some point.

**Comment by dasormeter** [comment] 2019-05-21 14:44
possible fix here https://github.com/digital-asset/daml/pull/1262#event-2356269132

**Comment by garyverhaegen-da** [comment] 2019-05-21 14:48
> possible fix here [#1262 (comment)](https://github.com/digital-asset/daml/pull/1262#event-2356269132)

That PR introduces a change that seems to be online already, as it's the one adding the
```
connect-src 'self' ws://${config.http.hostname}:${config.http.port}/
```
property, which I believe has the wrong protocol for a secure websocket connection.

**Comment by bolek-wisniewski** [comment] 2019-05-21 15:11
thanks guys - the issue is fixed as per @garyverhaegen-da recommendations

**Comment by garyverhaegen-da** [comment] 2019-05-21 21:02
@bolek-wisniewski I can confirm that it is fixed on https://webide.daml.com — both that it now works in Safari for me and through:
```
$ curl -I https://webide.daml.com -s | grep content-security-policy
content-security-policy: default-src 'self'; connect-src 'self' wss://webide.daml.com/ ws://webide.daml.com/; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;
```

However, when looking [at the code on current master](https://github.com/digital-asset/daml/blob/b12b94163d94f2fef72affd9e0d389d3ab894395/web-ide/proxy/src/proxy.ts#L147), I still see:
```javascript
res.setHeader("Content-Security-Policy", `default-src 'self'; connect-src 'self' ws://${config.http.hostname}:${config.http.port}/; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;`)
```

Could you make a PR to update master to match what is currently deployed?

**Closed** 2019-05-22 20:31 UTC
Labels: component/webide
