### ISSUE TITLE
IDE throws errors after "Go to definition" to DA.Map

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#1417] opened 2019-05-28 06:14 UTC
Create a daml module containing

```
import DA.Next.Map as M
x : Map Text Text = M.fromList []
```

Now do a "Go to definition" on the `fromList`, which takes you to `DA.Map`. Now if you go back to your module with `Map.daml` still open, you get a random(?) selection of Prelude and Record related errors in your own module. Closing `Map.daml` _sometimes_ fixes them, sometimes doesn't fix them and sometimes changes the errors to completely new ones. It's all very erratic.

Peek definition does the same, but the errors only start appearing once the peek pane is closed.

Only solution seems to be to reload the window.

**Comment by sofiafaro-da** [comment] 2020-12-14 17:46
I just tested this in SDK 1.7.0 and in HEAD. Couldn't reproduce it with `DA.Next.Map`, so this seems to solved at least as of SDK 1.7.0.

For `DA.Map` and other CPP-using library modules, this is solved by #8278, which prevents the errors in the standard library.

**Comment by sofiafaro-da** [comment] 2020-12-14 17:49
Closing this for now.

**Closed by sofiafaro-da** 2020-12-14 17:49 UTC
Labels: component/ide-core, language, language/now
