### ISSUE TITLE
[TS-Bindings] Web socket multiplexing issues with multiple stream query submit

### ISSUE THREAD

**Issue by akshayshirahatti-da** [digital-asset/daml#12381] opened 2022-01-12 19:32 UTC
The stateful nature of the current code means that on multiple query submit there is an issue with preserving state , especially of [manager.wsQueriesChange](https://github.com/digital-asset/daml/blob/main/language-support/ts/daml-ledger/index.ts#L457) , where the order of operations lead to a corrupt state leading us to try to run re-connect logic for web socket closures , especially in instances where the overall queries has changed.

The means to reproduce this is via app [sales-eng/apps/marketplace-demo](https://github.com/DACH-NY/sales-eng/tree/master/apps/marketplace-demo) on the `defi` branch 

1. do a `daml start`
1. after the code gen is done, a `npm install` and `npm start` in a separate terminal
in the app, login as `Issuer` and navigate to `Distribution -> New`
1. if you just leave that page open for a couple of minutes you should see eventually the spinner reappear, indicating the all the websocket connections have dropped, this branch is on 2.0.0-snapshot.20211207.8608.0.c4d82f72

Possible solutions

1. Removing the `close` event listener when we are manually shutting down the websocket.
2. Tying up the close event listener behaviour to be dependent on specific [CloseEvent code](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent/code)

FYI changing the existing [onWsClose](https://github.com/digital-asset/daml/blob/main/language-support/ts/daml-ledger/index.ts#L611) to a logging only listener does make the problem go away on my local tests

**Comment by stefanobaghino-da** [comment] 2022-01-17 08:17
Duplicate of #12198

**Closed by stefanobaghino-da** 2022-01-17 08:17 UTC
Labels: component/daml2js, application-runtime
