### ISSUE TITLE
Integrate daml2ts into the SDK

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#4133] opened 2020-01-21 09:26 UTC
Tasks for the `daml2ts` executable:
- [ ] Put `daml2ts` in the SDK release tarball
- [ ] Make `daml2ts` callable as `daml codegen ts` or something similar
- [ ] Document how to use `daml2ts` in the experimental section on [docs.daml.com](https://docs.daml.com/)

Tasks for the TS support libraries
- [ ] Give better names to `daml-json-types` and `daml-ledger-fetch` (maybe `@daml/interface-types` and `@daml/ledger`or `@daml/json-api`?)
- [ ] Release both packages to [npmjs.com](https://www.npmjs.com/) when the SDK gets released
- [ ] Document how to use `daml-ledger-fetch` on [docs.daml.com](https://docs.daml.com/)
- [ ] Add API documentation for both packages to [docs.daml.com](https://docs.daml.com/)

**Comment by cocreature** [comment] 2020-01-21 09:43
Duplicate of #4132 :stuck_out_tongue:

**Closed by cocreature** 2020-01-21 09:43 UTC
Labels: language, language/now
