### ISSUE TITLE
Change Sandbox and JSON API daemon to default to 127.0.0.1 instead of 0.0.0.0

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#3205] opened 2019-10-16 15:12 UTC
If `--address` is not specified, both `daml sandbox` and `daml json-api` bind to `0.0.0.0` interface, which means all interfaces. It is more secure to default to `localhost`/`127.0.0.1` instead.

**Comment by garyverhaegen-da** [comment] 2020-03-05 16:12
I believe https://github.com/digital-asset/daml/pull/4576 changes the last instance of a tool binding to 0.0.0.0 in the entire SDK. At the very least I can confirm sandbox, json-api and scenarios now default to 127.0.0.1.

**Comment by garyverhaegen-da** [comment] 2020-03-05 16:22
Correction: it looks like the repl service at least is still listening to 0, at least when running our tests.

**Comment by garyverhaegen-da** [comment] 2020-03-06 10:45
repl-server has been patched to bind to 127.0.0.1 (#4863). I have still seen one very brief security pop-up while running tests but haven't had time to find which process was causing it.

**Comment by S11001001** [comment] 2020-04-09 20:16
Fixed in JSON API in #4576, and Sandbox...previously.

**Closed by S11001001** 2020-04-09 20:16 UTC
Labels: component/ledger
