### ISSUE TITLE
Switching tabs in VS Code is unpleasant

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#89] opened 2019-03-19 10:05 UTC
If I change between two code panes in VS Code then the scenario tips keep animating in each time. Any way to avoid that?

If I change between two scenario panes then any changes I've made (like showing the other view) disappear. With the latest changes it also flickers, taking a little while to load (a regression relative to what it had before).

**Comment by cocreature** [comment] 2020-03-09 15:12
I’m not entirely sure I understand the issue here but I am unable to reproduce this so closing.

**Closed by cocreature** 2020-03-09 15:12 UTC
Labels: language, language/next
