### ISSUE TITLE
Incorrect contract key lookups in Scenarios

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#5924] opened 2020-05-11 09:16 UTC
On branch `contract-key-docs-WIP` I created an example to illustrate how contract keys behave for different relationships between Parties and Contracts. It highlighted a few issues:

1. Some of the `submitMustFail` statements fail with low-level crashes similar to that described in #5903 
2. There are two lookups that I consider wrong. https://github.com/digital-asset/daml/blob/contract-key-docs-WIP/docs/source/daml/code-snippets/Keys.daml#L133-L146. Non-stakeholders should always get negative lookup results at interpretation time, which means positive lookups can never succeed.

The script version of 2. (below) fails correctly meaning scenarios and Sandbox are mismatched. All of this was tested on the latest 1.1.0 snapshot.

```
s : Script () = do

  -- Put four parties in the four possible relationships with a `Keyed`
  sig <- allocateParty "s" -- Signatory
  obs <- allocateParty "o" -- Observer
  divulgee <- allocateParty "d" -- Divulgee
  blind <- allocateParty "b" -- Blind

  keyedCid <- submit sig do createCmd Keyed with ..
  divulgercid <- submit divulgee do createCmd Divulger with ..
  submit sig do exerciseCmd divulgercid DivulgeKeyed with ..

  -- Now the signatory and observer delegate their choices
  sigDelegationCid <- submit sig do 
    createCmd Delegation with 
      sig
      delegees = [obs, divulgee, blind]
  obsDelegationCid <- submit obs do 
    createCmd Delegation with
      sig = obs
      delegees = [divulgee, blind]

  -- TESTING LOOKUPS AND FETCHES

  -- WRONG: Divulgee can do positive lookup with maintainer authority. 
  -- The lookup should return `None`.
  mcid <- submit divulgee do 
    exerciseCmd sigDelegationCid LookupKeyed with
      delegee = divulgee
      lookupKey = sig
  assert (mcid == Some keyedCid)
  -- WRONG: Divulgee can fetch with stakeholder authority
  -- Should fail as lookup is negative.
  (cid, keyed) <- submit divulgee do 
    exerciseCmd obsDelegationCid FetchKeyed with
      delegee = divulgee
      lookupKey = sig
  assert (keyedCid == cid)

  return ()
```

**Comment by remyhaemmerle-da** [comment] 2020-05-27 14:28
#6123 fixes point 2. 
Point 1 is duplicate of #5903

**Closed** 2020-05-27 14:27 UTC
