### ISSUE TITLE
@daml/ledger: Add multi query functionality

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#4711] opened 2020-02-26 09:47 UTC
The JSON API allows for sending multiple queries (or key lookups) in a single request, both for the streaming and the non-streaming endpoints. We should expose this functionality in `@daml/ledger` too and potentially also in `@daml/react`.

Since TypeScript does not have dependent types, we can't type this perfectly. However, we can type it correctly for requests containing up to `n` queries for some fixed `n`. I would suggest we start with `n = 3` and increase it later if there's demand.

**Comment by stefanobaghino-da** [comment] 2022-03-14 15:35
Looks like https://github.com/digital-asset/daml/issues/7036 was a duplicate of this one. Closing.

**Closed by stefanobaghino-da** 2022-03-14 15:35 UTC
Labels: component/js-ecosystem, team/app-runtime
