### ISSUE TITLE
Type error in DA.Internal.Prelude

### ISSUE THREAD

**Issue by rohanjr-da** [digital-asset/daml#1549] opened 2019-06-06 16:25 UTC
The IDE shows the following error in the `DA.Internal.Prelude` module:
```
error type checking value DA.Internal.Prelude.guard:
  type mismatch:
  * expected type:
      e1215507ff2966cd61ada9ea1cb67ef8ea2c93a0b94e74ad0faaf5d62ff4d7af:DA.Internal.Prelude:Applicative m
  * found type:
      DA.Internal.Prelude:Applicative m
  * expression:
      $dApplicative
```
You can find this for example by jumping to the definition of `getParty`.

**Comment by cocreature** [comment] 2019-06-07 07:35
This is related to https://github.com/digital-asset/daml/issues/1417. I am not really sure how feasible it is to load two different packages into the same IDE session in general so we might want to consider to try and open files in different packages in a new session somehow.

**Comment by cocreature** [comment] 2020-02-05 16:18
Closing as a duplicate of #1417

**Closed by cocreature** 2020-02-05 16:18 UTC
Labels: component/ide-core, language
