### ISSUE TITLE
Remove implicit party allocation in Daml on SQL

### ISSUE THREAD

**Issue by SamirTalwar-DA** [digital-asset/daml#6895] opened 2020-07-28 12:35 UTC
Currently, in line with Sandbox, Daml on SQL allocates parties implicitly when an unknown party appears in a transaction. However, Daml on SQL is intended as a production-level offering, and this feature can be dangerous in production, as parties might be mis-referenced. Most users of a ledger would expect an error when they typo "Alice" as "Alise", not a new party.

@stefanobaghino-da, @gerolf-da and I suggest we remove implicit party allocation from Daml on SQL, in line with all other production-level ledgers. All parties will have to be allocated implicitly through the party management service.

**Comment by stefanobaghino-da** [comment] 2020-07-28 14:58
I wholeheartedly agree with the proposal. Implicit party allocation can lead (due to a simple typo) to bugs and unexpected behavior on a production ledger, where I expect users to be provided with authorization tokens. A production-grade ledger cannot refer to parties that have not gone through some form of party on-boarding.

**Comment by SamirTalwar-DA** [comment] 2020-07-29 08:15
I tried setting `implicitPartyAllocation = false` in the DAML on SQL configuration, but unfortunately it doesn't seem to have any effect (at least according to `ClosedWorldIT`, which still fails). There's something going on inside the Sandbox Classic codebase that allocates the parties anyway.

Full patch; let me know if I missed anything:

```diff
diff --git a/ledger/daml-on-sql/BUILD.bazel b/ledger/daml-on-sql/BUILD.bazel
index b7bb191a3..763747487 100644
--- a/ledger/daml-on-sql/BUILD.bazel
+++ b/ledger/daml-on-sql/BUILD.bazel
@@ -122,8 +122,4 @@ conformance_test(
         "--port=6865",
         "--eager-package-loading",
     ],
-    test_tool_args = [
-        "--open-world",
-        "--exclude=ClosedWorldIT",
-    ],
 )
diff --git a/ledger/daml-on-sql/src/main/scala/on/sql/package.scala b/ledger/daml-on-sql/src/main/scala/on/sql/package.scala
index 6836a058f..d2263a228 100644
--- a/ledger/daml-on-sql/src/main/scala/on/sql/package.scala
+++ b/ledger/daml-on-sql/src/main/scala/on/sql/package.scala
@@ -15,6 +15,7 @@ package object sql {
   private[sql] val DefaultConfig = SandboxConfig.defaultConfig.copy(
     participantId = v1.ParticipantId.assertFromString(Name.unwrap.toLowerCase()),
     ledgerConfig = LedgerConfiguration.defaultLedgerBackedIndex,
+    implicitPartyAllocation = false,
   )
 
 }
diff --git a/ledger/sandbox-classic/src/main/scala/platform/sandbox/SandboxServer.scala b/ledger/sandbox-classic/src/main/scala/platform/sandbox/SandboxServer.scala
index 7ff46f01a..9ff8c2d1d 100644
--- a/ledger/sandbox-classic/src/main/scala/platform/sandbox/SandboxServer.scala
+++ b/ledger/sandbox-classic/src/main/scala/platform/sandbox/SandboxServer.scala
@@ -322,9 +322,8 @@ final class SandboxServer(
         timeProviderType = timeProviderType,
         ledgerConfiguration = ledgerConfiguration,
         commandConfig = config.commandConfig,
-        partyConfig = PartyConfiguration.default.copy(
-          // sandbox-classic always allocates party implicitly
-          implicitPartyAllocation = true,
+        partyConfig = PartyConfiguration(
+          implicitPartyAllocation = config.implicitPartyAllocation,
         ),
         optTimeServiceBackend = timeServiceBackendO,
         metrics = metrics,
```

**Comment by stefanobaghino-da** [comment] 2020-07-29 08:16
As you already mentioned offline, let's hold this off until we can make some clarity around this feature.

**Comment by cocreature** [comment] 2021-02-02 08:51
Can we close this? afaik, we’ve killed implicit party allocation in daml on sql.

**Comment by gerolf-da** [comment] 2021-04-13 07:48
Closing as this has been fixed.

**Closed by gerolf-da** 2021-04-13 07:48 UTC
Labels: component/ledger
