### ISSUE TITLE
Add a `fetch` equivalent to DAML Script

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#7286] opened 2020-09-01 07:54 UTC
A fairly common use case in Scenarios was to fetch a contract from a ContractId and test some properties:

```
submit p do
  args <- fetch cid
  assert (someCheck args)
```

Unless there's only a single instance of the template type visible to `p`, the `query` function is a bit awkward to use instead so I'd like a function `queryCid : Party -> ContractId a -> Script (Optional a)`. Feel free to choose a better name, of course.

WIth such a function I could write top-level

```
Some (args) <- queryCid p cid
assert (someCheck args)
```

This is more natural than what's available in Scenarios as applications don't get contracts using DAML-level `fetch`, but a local query.

Equivalents for REPL and Triggers would be nice, of course.

**Comment by cocreature** [comment] 2020-09-01 08:00
Duplicate of #7282

**Closed by cocreature** 2020-09-01 08:00 UTC
