### ISSUE TITLE
Error: Conflicting definitions for ‘arg’

### ISSUE THREAD

**Issue by tweber-da** [digital-asset/daml#3017] opened 2019-09-25 08:30 UTC
The following snippet
```
template Foo
  with
    p : Party
  where
    signatory p

    controller p can
      FooC: ()
        with
          arg : Decimal
        do
          return ()
```
fails with 
```
 • Conflicting definitions for ‘arg’
      Bound at: ...
                <no location info>
    • In an equation for ‘_actionFooFooC’
```

**Comment by hurryabit** [comment] 2019-09-26 12:59
The problem is that the choice argument is implicitly bound to an variable called `arg`. That's why we have a conflict. The error message is pretty bad. Unfortunately, I don't see how to easily improve the error message.

The workaround for now is to not call your choice fields `arg`.

In the long term, we could change the template desugaring such that we don't bind the choice argument to `arg` if there's a field called `arg`. Given the simplicity of the workaround, I won't give this high priority.

**Comment by cocreature** [comment] 2020-07-17 14:41
Closing since I don’t see this getting fixed.

**Comment by hurryabit** [comment] 2020-07-21 16:44
I would like to keep this one open since it's something we should consider if and when we change the compiler architecture.

**Comment by cocreature** [comment] 2020-07-21 16:46
Fair enough although I expect that changing the compiler architecture will change so much that very specific issues like this one are useless.

**Comment by akrmn** [comment] 2022-05-06 13:59
Closing in favor of https://github.com/digital-asset/daml/issues/13811

**Closed by akrmn** 2022-05-06 13:59 UTC
Labels: language/later, language
