### ISSUE TITLE
with-syntax does not support doc comments before record fields

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#14947] opened 2022-09-06 12:51 UTC
In the example below R1 is processed correctly by daml-docs while R2 produces a parse error.
Putting the docs afterwards via `-- ^` works but I find the first style usuall easier to read.

```
module Test where

data R1 = R1
  { -- | doc a
  a : ()
  -- | doc b
  , b : ()
  }

data R2 = R2
  with
    -- | doc a
    a : ()
    -- | doc b
    b : ()
```

**Comment by moisesackerman-da** [comment] 2024-03-19 09:54
Duplicate of https://github.com/digital-asset/daml/issues/1141

**Closed by moisesackerman-da** 2024-03-19 09:54 UTC
Labels: language
