### ISSUE TITLE
Streaming JSON API: Make error behavior consistent and document it

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#4521] opened 2020-02-14 12:08 UTC
To be honest, I don't fully understand the current error behavior. Here's something I've observed:

1. When I send a request that is syntactically wrong, I get the message
`
{"error":"Endpoints.InvalidUserInput: JsonReaderError. Cannot read JSON: <{}>. Cause: spray.json.DeserializationException: Object is missing required member 'templateIds'"}
`
and the stream carries on. I would expect the stream to be closed since there'll never be any events.
2. When I send a request with an empty list of template ids, I get the message
`
{"error":"Endpoints.InvalidUserInput: JsonReaderError. Cannot read JSON: <{\\"templateIds\\":[]}>. Cause: spray.json.DeserializationException: search requires at least one item in 'templateIds'"}
`
and the stream carries on. Again, I would expect the stream to be closed.
3. When I send a request with one template id that is bogus, I get a message like
`
{"error":"Cannot resolve any templateId from request: GetActiveContractsRequest(Set(TemplateId(Some(bbbbfec7d278f3ac692e82fa94f1f4a322576abe043cdb7b490c67d1e10214d2),DAVL,EmployeeProposalX)),Map()), unresolved templateIds: Set(TemplateId(Some(bbbbfec7d278f3ac692e82fa94f1f4a322576abe043cdb7b490c67d1e10214d2),DAVL,EmployeeProposalX))"}
`
and the stream carries on. I would expect the stream to be closed again.
4. When I send a second request on a connection, it gets silently dropped on the floor.

I have a few thoughts about this:

1. For the sake of consistency with other endpoints, it would make sense to change error message to a format like `{"errors": [...]}`?
2. Whenever the list of valid queries is empty or the query is completely bogus, shouldn't we close the stream immediately?
3. Would it make sense to send warnings for all template ids that cannot be resolved and send an error if the list of template ids that can be resolved is empty? Thus, a query containing only invalid template ids would first have a warning for each template id that it cannot be resolved and then an error that there are no template ids that can be resolved. Sending an empty list of template ids would not trigger the warning but only the error.
4. We should send an error message for each request that gets sent after the first request.

Whatever we agree on, we need better documentation for this. Currently, I can't find any mention of error messages on the streaming endpoints at all.

**Comment by leo-da** [comment] 2020-03-19 19:05
@hurryabit I agree with all the items in your list. The only thing I would add is status code for the error response... so it is
```
 {"errors": [...], "status": <400 | 401 | 404 | 500> }
```
status codes are not defined for the websocket, but I believe it makes sense to provide an error/status code. It will be consistent between synchronous and streaming APIs.

The client would know that everything that is 400 is user input error, 500 server-side, 401 authentication/authorization error. Error codes documented here: https://docs.daml.com/json-api/index.html#error-reporting

**Comment by hurryabit** [comment] 2020-03-24 09:40
Adding the status code sounds very reasonable. Good idea.

**Comment by leo-da** [comment] 2020-03-24 18:48
need to write a test for the item 4. Don't really know if we (Akka HTTP) allows re-using the same websocket connection in multiple requests.

@hurryabit do you need to be able to send multiple streaming queries one at a time? 
```
ws.send(`{"templateIds": ["a:b"]}`)
ws.send(`{"templateIds": ["c:d"]}`)
```
and do you expect it to receive contracts matching both templates, similar to:
```
ws.send(`{"templateIds": ["a:b", "c:d"]}`)
```

**Comment by S11001001** [comment] 2020-03-24 18:50
@leo-da We discussed this when first implementing websockets; the decision was they must be specified all at once (single object) up front, with "one at a time" (i.e. dynamic update) reserved for later if at all.

**Comment by leo-da** [comment] 2020-03-24 19:09
> We should send an error message for each request that gets sent after the first request.

I think we should return an error and drop the established connection, does not matter if we are already streaming over it... if you try to re-use it, we kill it. What do you think @S11001001 ? The doc will reflect it.

**Comment by leo-da** [comment] 2020-03-24 19:18
another thing... we should consider changing the design a bit... Unrecoverable errors supposed to be reported as error events to the websocket client. Client expected to register a listener for this kind of events:
```
ws.on("error", function incoming(error) {
  console.log(`error: ${JSON.stringify(error)}`)
})
```

Bad news Akka HTTP does not expose an API to report such errors to the client. See 
- https://github.com/akka/akka-http/issues/2458

The issue has not been assigned yet. We need to decide what we are going to do. Not having `error` events looks wrong to me. We can
a). wait for the fix,
b). we can contribute a fix or
c) we can switch to another Websocket implementation (costly).

**Comment by hurryabit** [comment] 2020-03-25 11:06
My understanding of the docs I could find around error handling for WebSockets is that the `"error"` event is fired if, for example, the network connections gets dropped or there's a decoding error. There doesn't seem to be a way to send messages from the server to trigger this callback.

However, when you close a WebSocket connection you can give an error code (they are not HTTP status codes) and an error message. Is that something we could leverage? How do apps serving data over WebSockets handle this?

**Comment by leo-da** [comment] 2020-03-25 14:17
https://tools.ietf.org/html/rfc6455#section-7.1.6
https://tools.ietf.org/html/rfc6455#section-7.1.7

Yep, you trigger "unrecoverable" error event closing the connection with an appropriate error code and optional Connection Close Reason (different from HTTP status code).

We should trigger error event when dropping a connection (that is what client expects), e.g. when template IDs are empty or we could not resolve any of the passed template IDs.

The problem is with Akka HTTP support for WebSockets. It does not currently allow closing WebSocket connection explicitly with an error code and reason.

In any case, need to find a good tutorial on Websocket best practices. I have been looking at Slack WebSocket-based API: https://api.slack.com/rtm.

**Comment by leo-da** [comment] 2020-03-26 17:44
### meeting notes
- we would postpone implementing unrecoverable errors over error events (Akka HTTP does not have provide an API for this right now, this does not buy as a lot, we already close connection on unrecoverable errors, see #5141)
- we would document that we close connection when encounter unrecoverable error, e.g. invalid JSON request, empty template IDs
- still need to handle item `4. We should send an error message for each request that gets sent after the first request.`

**Closed** 2020-03-31 18:38 UTC
Labels: component/json-api, discussion, wip-issue
