### ISSUE TITLE
implement Enum Text and lowercase, uppercase conversion.

### ISSUE THREAD

**Issue by leonidr-da** [digital-asset/daml#11132] opened 2021-10-05 22:03 UTC
Can we add to the stdlib:

```
ub : Int
ub = 1114112 -- = 17 * 65,536

cplToI : [Int] -> Int
cplToI l = fst $ foldl u (0, 1) l
  where u (a, p) i = (a + i * p, p * ub)

iToCplAcc : [Int] -> Int -> [Int]
iToCplAcc acc i =
  let d = i / ub in
  if d == 0 then
    i :: acc
  else
    iToCplAcc (i::acc) (i - d * ub)

iToCpl : Int -> [Int]
iToCpl = iToCplAcc []

instance Enum Text where
  fromEnum = cplToI . toCodePoints
  toEnum = fromCodePoints . iToCpl
```

my goal is to also add
```
ia = fromEnum "a"
iz = fromEnum "z"

iA = fromEnum "A"
iZ = fromEnum "Z"

toUpperAsciiChar : Text -> Text
toUpperAsciiChar c
  | ia <= ic && ic <= iz = toEnum (ic + (iA - ia))
  | otherwise = c
      where ic = fromEnum c

toLowerAsciiChar : Text -> Text
toLowerAsciiChar c
  | iA <= ic && ic <= iZ = toEnum (ic - (iA - ia))
  | otherwise = c
      where ic = fromEnum c

toUpper : Text -> Text
toUpper = implode . fmap toUpperAsciiChar . explode

toLower : Text -> Text
toLower = implode . fmap toLowerAsciiChar . explode
```

But if  there are primitives that we can leverage that accomplish `toLower` and `toUpper` better (ala explode), that would  be great.

**Comment by akrmn** [comment] 2021-10-06 09:43
I agree that it would be nice to have `toLower` and `toUpper` (perhaps more generally even `mapChars : (Text -> Text) -> Text -> Text` (where the function argument is really a function on characters)). 

However, I don't think that an Enum instance is necessary for that. There's also the problem that your encoding overflows the 64-bit `Int` after 4-char strings (try `fromEnum "\0\0\0\0"`). 

I think I'd tweak your definitions of `toUpper` and `toLower` like this instead, to avoid the need for `to/fromEnum`:

```haskell
toUpper : Text -> Text
toUpper = fromCodePoints . fmap toUpperCP . toCodePoints
  where
    toUpperCP cpc
      | cpa <= cpc && cpc <= cpz = cpc + (cpA - cpa)
      | otherwise = cpc
    [cpA, cpZ, cpa, cpz] = toCodePoints "AZaz" 
```

**Comment by akrmn** [comment] 2021-10-06 10:38
After digging a bit, I found that there are already two primitives `BETextToUpper` and `BETextToLower`,

https://github.com/digital-asset/daml/blob/4cb521b406424f471d9324e17efa7a45d3774b45/compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Base.hs#L367-L368

but they're marked as experimental/unstable. I also found their implementation,

https://github.com/digital-asset/daml/blob/4cb521b406424f471d9324e17efa7a45d3774b45/daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/SBuiltin.scala#L1578-L1596

judging by the `TODO`s, it seems like the unstable bit comes from not being sure if we want the primitives to do ASCII-only case conversion or all-Unicode. I believe the latter runs into stuff like `ß => SS`.

Perhaps a better way to close this issue would be to make the choice, or split each into two well-defined privimitives for ASCII and all-Unicode.

**Comment by leonidr-da** [comment] 2021-10-06 12:10
All of that makes sense to me, I thought that I would get more traction with some kind of implementation than without. Adding a `toLowerAscii` and `toUpperAscii` would be great.

ASCII4Eva!!!

**Comment by remyhaemmerle-da** [comment] 2021-10-06 15:52
We added those experimental primitives to run some performance tests with one of the DAML code base we develop internally. As far I am aware, we were unable to improve noticeably the performance of this application. 

In regards to adding those particular builtins in LF,  my answer is the same as for any new builtins. As builtins are expensive to maintain, If there is no clear benefit, I prefer we implement those in DAML directly. 
We may revisit this in the future.

In regards to adding `to{Lower,Upper}Ascii` to the standard library, I looks reasonable to me, however I will  let @cocreature and @sofiafaro-da be judge.

**Comment by akrmn** [comment] 2021-10-06 16:25
@remyhaemmerle-da 
Thanks for weighing in! I was wrongly assuming that there would be a performance benefit to having these as builtins, but given your comment we can discard that idea. 

Having them in the standard library would probably be fine for now, but eventually I guess we could split functions like these into a `da-text` dependency(?)

**Comment by remyhaemmerle-da** [comment] 2021-10-06 16:46
@moisesackerman-da There were no clear performance benefit in the use cases we studied. 
We may reconsider expending the number of text preprocessing primitives, if we have clear evidence of the benefit they bring.

More generally, I believe that text processing is something you should try to do off-ledger as DAML will be inevitably slow for this kind of task. I do not say, there is no legitimate use cases, but if you process text with parsimony slow implementation should not be a killer.

**Comment by remyhaemmerle-da** [comment] 2021-10-06 19:24
@leonidr-da I do not say, there is no legitimate use cases  :wink:, I even supported the addition of the function to the standard library.  I am just a bit reluctant to add new LF primitives each time we find Daml too "slow".

On the one hand, adding primitives does not solve the intrinsic problem of slowness, but just circumvent it in some particular use cases. On the other hand, solving really Daml slowness will require rewriting the interpreter, the fewer primitives we have the easier this task will be.

**Comment by cocreature** [comment] 2021-10-11 07:06
Adding it to the standard library seems very reasonable to me. I agree with @remyhaemmerle-da that we should be careful wtr to primitives. I do expect that we’ll want to expand the set of Text primitives at some point but I’d rather do that in one go accompanied by design & benchmark work to only add the ones that really pay off instead of adding more and more primitives over time.

**Comment by leonidr-da** [comment] 2021-10-11 14:49
@akrmn Could you add your proposed functions? I am not that interested in `Enum Text` as much as having a good `toUpper` and `toLower` and don't want to deal with the complexities of Unicode that @stephencompall-DA's mentioned  elsewhere.

**Closed** 2021-12-10 17:14 UTC
